spring.application.name=Wolf_of_Wright_Street

# MariaDB connection information
spring.datasource.url=jdbc:mariadb://localhost:3307/Wolf_of_Wright_Street
spring.datasource.username=user
spring.datasource.password=password
# Needed for Case Sensitive Tables and Columns
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server.servlet.context-path=/Wolf_of_Wright_Street_Service
